C:\Apps, Faster benchmark, IIS Events, Build Web-Asp-Net, Web-Asp-Net45, Test-Windows-Docker-Images.yml [skip ci]

diff --git a/.github/workflows/Test-Windows-Docker-Images.yml b/.github/workflows/Test-Windows-Docker-Images.yml
--- a/.github/workflows/Test-Windows-Docker-Images.yml
+++ b/.github/workflows/Test-Windows-Docker-Images.yml
@@ -164,7 +164,9 @@ jobs:
         docker run -d --name beast --isolation=hyperv "the:$NEWTAG"
         # it will add image magick to path
         docker exec beast choco install imagemagick
-        docker exec beast cmd /c echo %PATH% | tee "$SYSTEM_ARTIFACTSDIRECTORY/PATH-IMAGEMAGICK-$SUFFIX.txt" || echo "ERROR echo PATH"
+        echo " "
+        docker exec beast powershell -c '$ENV:PATH' | tee "$SYSTEM_ARTIFACTSDIRECTORY/PATH-IMAGEMAGICK-$SUFFIX.txt" || echo "ERROR echo PATH"
+        echo " "
         docker exec beast magick --version || echo "ERROR magick --version"
         docker rm -f beast
 
