PUSH. C:\Apps, Faster benchmark, IIS Events, Build Web-Asp-Net, Web-Asp-Net45, Test-Windows-Docker-Images.yml [skip ci]

diff --git a/.github/workflows/Test-Windows-Docker-Images.yml b/.github/workflows/Test-Windows-Docker-Images.yml
--- a/.github/workflows/Test-Windows-Docker-Images.yml
+++ b/.github/workflows/Test-Windows-Docker-Images.yml
@@ -173,7 +173,7 @@ jobs:
         docker exec beast powershell -c '$ENV:PATH' | tee "$SYSTEM_ARTIFACTSDIRECTORY/PATH-FFMPEG-$SUFFIX.txt" || echo "ERROR echo PATH"
         echo " "
         echo "FFMPEG VERSION is BELOW"
-        docker exec beast ffmpeg -version | tee "$SYSTEM_ARTIFACTSDIRECTORY/FFMPEG-STATUS-$SUFFIX.txt" || echo "ERROR ffmpeg --version"
+        docker exec beast ffmpeg -version | tee "$SYSTEM_ARTIFACTSDIRECTORY/FFMPEG-STATUS-$SUFFIX.txt" || echo "ERROR ffmpeg -version"
         docker rm -f beast
 
     - name: PUSH THE TAG ${{ env.THEIMAGE }}:${{ env.NEWTAG }}
