C:\Apps, Faster benchmark, IIS Events, Build Web-Asp-Net, Web-Asp-Net45, Test-Windows-Docker-Images.yml [skip ci]

diff --git a/.github/workflows/Test-Windows-Docker-Images.yml b/.github/workflows/Test-Windows-Docker-Images.yml
--- a/.github/workflows/Test-Windows-Docker-Images.yml
+++ b/.github/workflows/Test-Windows-Docker-Images.yml
@@ -163,12 +163,12 @@ jobs:
         set -o pipefail
         docker run -d --name beast --isolation=hyperv "the:$NEWTAG"
         # it will add image magick to path
-        docker exec beast choco install imagemagick
+        docker exec beast choco install imagemagick --version 6.8.2.6 || docker exec beast choco install imagemagick --version 6.8.3.10
         echo " "
         echo "PATH is BELOW"
         docker exec beast powershell -c '$ENV:PATH' | tee "$SYSTEM_ARTIFACTSDIRECTORY/PATH-IMAGEMAGICK-$SUFFIX.txt" || echo "ERROR echo PATH"
         echo " "
-        docker exec beast magick --version || echo "ERROR magick --version"
+        docker exec beast magick --version | tee "$SYSTEM_ARTIFACTSDIRECTORY/IMAGEMAGICK-STATUS-$SUFFIX.txt" || echo "ERROR magick --version"
         docker rm -f beast
 
     - name: Upload artifacts 
