Test Workflow, Enable IIS Remote Management, PUSH. C:\Apps, Faster benchmark, IIS Events, Build Web-Asp-Net, Web-Asp-Net45, Test-Windows-Docker-Images.yml [skip ci]

diff --git a/.github/workflows/Test-IIS-Windows-Docker-Images.yml b/.github/workflows/Test-IIS-Windows-Docker-Images.yml
--- a/.github/workflows/Test-IIS-Windows-Docker-Images.yml
+++ b/.github/workflows/Test-IIS-Windows-Docker-Images.yml
@@ -74,13 +74,14 @@ jobs:
          Wait-For-HTTP http://localhost:8080 30 || echo "ERROR: Wait-For-HTTP http://localhost:8080"
          try-and-retry curl -I http://localhost:8080
          try-and-retry curl http://localhost:8080
-         time docker exec iis bombardier.exe -c 20 -d 20s --print=result -k -s http://localhost:80 | tee "$SYSTEM_ARTIFACTSDIRECTORY\Stress Container ${{ matrix.TAG }} as ${{ matrix.ISOLATION }}.txt"; || echo "ERROR bombardier.exe"
+         time docker exec iis bombardier.exe -c 20 -d 20s --print=result -k -s http://localhost:80 | tee "$SYSTEM_ARTIFACTSDIRECTORY\Stress Container ${{ matrix.TAG }} as ${{ matrix.ISOLATION }}.txt" || echo "ERROR bombardier.exe"
 
          echo " "; echo "IIS CONTAINER LOGS"
          docker logs --since 0 iis
 
     - name: 'HOST: Run and Curl'
       shell: bash
+      if: always()
       run: |
          set -eu; set -o pipefail
          docker cp iis:C:\\Apps\\Bombardier.exe C:\\Windows\\
