C:\Apps, Faster benchmark, IIS Events, Build Web-Asp-Net, Web-Asp-Net45, Test-Windows-Docker-Images.yml [skip ci]

diff --git a/.github/workflows/Test-Windows-Docker-Images.yml b/.github/workflows/Test-Windows-Docker-Images.yml
--- a/.github/workflows/Test-Windows-Docker-Images.yml
+++ b/.github/workflows/Test-Windows-Docker-Images.yml
@@ -170,7 +170,8 @@ jobs:
         echo "PATH is BELOW"
         docker exec beast powershell -c '$ENV:PATH' | tee "$SYSTEM_ARTIFACTSDIRECTORY/PATH-FFMPEG-$SUFFIX.txt" || echo "ERROR echo PATH"
         echo " "
-        docker exec beast ffmpeg --version | tee "$SYSTEM_ARTIFACTSDIRECTORY/FFMPEG-STATUS-$SUFFIX.txt" || echo "ERROR ffmpeg --version"
+        echo "FFMPEG VERSION is BELOW"
+        docker exec beast ffmpeg -version | tee "$SYSTEM_ARTIFACTSDIRECTORY/FFMPEG-STATUS-$SUFFIX.txt" || echo "ERROR ffmpeg --version"
         docker rm -f beast
 
     - name: Upload artifacts
